name: langsets
channels:
  - conda-forge  
  - microsoft
  - defaults
dependencies:
  - python=3.10
  - beautifulsoup4
  - playwright # Disable VPN for further installation and use: https://askubuntu.com/questions/1114392/disable-ssl-certificate-validation-in-ubuntu-totally
  - python-dotenv
  - pip
  - pip:
    - chromadb
    - duckduckgo-search
    - html2text
    - langchain
    - openai
    - tiktoken